dist: trusty
sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
matrix:
  allow_failures:
    - python: "nightly"

install:
  - pip install coveralls tox-travis
script:
  - tox
after_success:
  - coveralls
